# .github/workflows/pairbot.yml
# This file schedules the Slack pair bot to run bi-weekly using GitHub Actions

name: Slack Pair Bot

on:
  schedule:
    - cron: '0 15 * * 2'  # every Tuesday at 15:00 UTC (9 AM Mountain Time)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        run: python slack_pair_bot.py
