# .github/workflows/pairbot.yml
# This file schedules the Slack pair bot to run bi-weekly using GitHub Actions

name: Slack Pair Bot

on:
  schedule:
    - cron: '0 12 */14 * *'  # every 14 days at 12:00 UTC
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        run: python slack_pair_bot.py

# .gitignore
__pycache__/
*.pyc
pairs.db

# README.md
# Slack Pair Bot

Pairs random users in a Slack channel every two weeks.

## Setup
1. Create a Slack app with required scopes: `channels:read`, `chat:write`, `users:read`, `conversations.members`
2. Install the app and get your Bot Token and Channel ID.
3. Set GitHub secrets:
   - `SLACK_BOT_TOKEN`
   - `SLACK_CHANNEL_ID`
4. Push code to GitHub. It runs automatically every two weeks.

## Local Testing
```bash
export SLACK_BOT_TOKEN=your-token
export SLACK_CHANNEL_ID=your-channel-id
python slack_pair_bot.py
```
